### ISSUE TITLE
1.2.8 did not compile

### ISSUE THREAD

**Issue by M5oul** [c-geek/naclb#1]
```fish
> naclb@1.2.8 install /root/ucoin/node_modules/vucoin/node_modules/naclb
> node-pre-gyp install --fallback-to-build

make: Entering directory '/root/ucoin/node_modules/vucoin/node_modules/naclb/build'
  CXX(target) Release/obj.target/naclb/nacl.o
../nacl.cc:2:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
naclb.target.mk:91: recipe for target 'Release/obj.target/naclb/nacl.o' failed
make: *** [Release/obj.target/naclb/nacl.o] Error 1
make: Leaving directory '/root/ucoin/node_modules/vucoin/node_modules/naclb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.1-sunxi
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm/naclb.node" "--module_name=naclb" "--module_path=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm"
gyp ERR! cwd /root/ucoin/node_modules/vucoin/node_modules/naclb
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm/naclb.node --module_name=naclb --module_path=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/ucoin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.4.1-sunxi
node-pre-gyp ERR! command "/usr/bin/nodejs" "/root/ucoin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/ucoin/node_modules/vucoin/node_modules/naclb
node-pre-gyp ERR! node -v v5.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.23
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm/naclb.node --module_name=naclb --module_path=/root/ucoin/node_modules/vucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-arm' (1)
- tweetnacl@0.14.0 node_modules/sshpk/node_modules/tweetnacl
```

**Comment by c-geek** [comment]
The module should compile on ARM now.

Maybe uCoin will too, using [installation procedure](https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node). Given you don't use a Raspberry PI with 256MB RAM since it is not enough for packages compilation process.

**Comment by M5oul** [comment]
It compile :+1: 
Thanks.
